### ISSUE TITLE
Not able to console.log returned JSON object

### ISSUE THREAD

**Issue by harrishutchison** [karlsander/spotify-url-info#53]
Using version 1.4.0, using the following code to return JSON object of a Spotify URL:
`await getPreview(this.post.URL).then((result) => {
  console.log(result.image);
});`

Getting this error in console when trying to log result.image/any other property of the object. Also when trying to print the object itself: https://imgur.com/a/20cfpEz

`this.post.URL` is definitely a valid Spotify URL, it is parsed previously in the function.

**Comment by karlsander** [comment]
The issue here is CORS. The spotify embed url is not sending an `Access-Control-Allow-Origin` header that allows you to make requests from a web app. The [MDN article on CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is decent, if not straightforward.

I'm kind of embarrased I never noticed this, as I only use the library in react-native and node contexts where CORS is not an issue, others seem to be using it in discord bots etc, which also run in node I assume. I wonder if its always been the case or spotify added this recently?

I guess this whole approach simply doesn't work in the browser, actually. I don't really see a good way to circumvent that on the library side without using another approach alltogether. I will try it some more and add a warning to the readme.

For you there is a way to circumvent this, though it may not be worth it (or you solved it with another method by now): Use some kind of proxy between the browser and spotify. There are generic ones, that simply forward any request and add the right allow headers to the response. You can find self hosted and hosted options if you google for `cors-proxy`. Or you can set up something like a serverless function (if you have that option in your app) that actually uses this library to make the request and then use that from your app.

**Comment by harrishutchison** [comment]
That's sort of what I suspected to be the problem. If I get the change I will go back and try with CORS disabled in the browser.

Thanks for your detailed reply.
